name: Regenerate openapi-connector

on:
    workflow_dispatch:

jobs:
    call_workflow:
        name: Run Regenerate Connector Workflow
        # if: ${{ github.repository_owner == 'ballerina-platform' }}
        uses: chathushkaayash/ballerina-library/.github/workflows/regenerate-connector-template.yml@main
        secrets: inherit
