name: Update openapi-connector

on:
  workflow_dispatch:
    inputs:
      openapi_url:
        description: "URL of the OpenAPI JSON"
        required: false
        type: string
      flatten_openapi:
        description: "Enable OpenAPI Flattening"
        required: false
        type: boolean
        default: false
      align_openapi:
        description: "Enable OpenAPI Alignment"
        required: false
        type: boolean
        default: false
      disable_checks:
        description: "Disable PR checks"
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Update openapi-connector
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BALLERINA_BOT_TOKEN }}

      - name: Get Ballerina Version
        run: |
          BAL_VERSION=$(grep -w 'ballerinaLangVersion' gradle.properties | cut -d= -f2 | rev | cut --complement -d- -f1 | rev)
          if [ -z "$BAL_VERSION" ]; then
              BAL_VERSION="latest"
          fi
          echo "BAL_VERSION=$BAL_VERSION" >> $GITHUB_ENV
          echo "Ballerina Version: $BAL_VERSION"

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.3
        with:
          version: ${{ env.BAL_VERSION }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21.0.3

      - name: Set ENV Variables
        run: |
          echo -e '${{ toJson(secrets) }}' | jq -r 'to_entries[] | .key + "=" + .value' >> $GITHUB_ENV

      - name: Remove Existing Client Files
        working-directory: ballerina
        run: |
          rm -f client.bal utils.bal types.bal

      - name: Download or Copy openapi.json
        run: |
          if [ -n "${{ inputs.openapi_url }}" ]; then
            echo "Downloading openapi.json from provided URL..."
            wget -O ballerina/openapi.json "${{ inputs.openapi_url }}"
          else
            echo "Using existing openapi.json from docs/spec directory..."
            cp docs/spec/openapi.json ballerina/openapi.json
          fi

      - name: Flatten OpenAPI Specification
        if: ${{ inputs.flatten_openapi }}
        working-directory: ballerina
        run: |
          echo "Flattening OpenAPI Specification..."
          bal openapi flatten -i openapi.json
          mv flattened_openapi.json openapi.json

      - name: Align OpenAPI Specification
        working-directory: ballerina
        if: ${{ inputs.align_openapi }}
        run: |
          echo "Aligning OpenAPI Specification..."
          bal openapi align -i openapi.json
          mv aligned_ballerina_openapi.json openapi.json

      - name: Generate Ballerina Code
        working-directory: ballerina
        run: |
          echo "Generating Ballerina code from OpenAPI Specification..."
          bal openapi -i openapi.json --mode client

      - name: Clean Up Intermediate Files
        working-directory: ballerina
        run: rm -f openapi.json

      - name: Build the Package
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: |
          ./gradlew build -x test
          ./gradlew test

      - name: Configure Git Identity
        run: |
          git config user.name "chathushkaayash"
          git config user.email "chathushkaayash@gmail.com"

      - name: Commit and Push Changes
        id: commitChanges
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: |
          git checkout -b update-openapi-connector-${{ github.run_number }}
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            echo "hasChanged=true" >> $GITHUB_OUTPUT
            git commit -m "[Automated] Update Ballerina OpenAPI Connector"
            git push origin update-openapi-connector-${{ github.run_number }}
            gh pr create \
              --title "Update OpenAPI Connector" \
              --body "Automated update of the OpenAPI-based Ballerina connector." \
              --base main \
              --head update-openapi-connector-${{ github.run_number }}
            echo "Pull request created successfully."
          fi

      - name: Check PR Build
        if: ${{ steps.commitChanges.outputs.hasChanged && !inputs.disable_checks }}
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: |
          echo "Waiting for checks to complete..."
          gh pr checks update-openapi-connector-${{ github.run_number }} --required --watch --interval 20
          sleep 5

      - name: Merge PR
        if: ${{ steps.commitChanges.outputs.hasChanged }}
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: |
          gh pr merge update-openapi-connector-${{ github.run_number }} --merge --delete-branch
          echo "Pull request merged successfully."
