name: Update openapi-connector

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      openapi_url:
        description: "URL of the OpenAPI JSON (Optional)"
        required: false
        type: string
      flatten_openapi:
        description: "Enable OpenAPI Flattening?"
        required: false
        type: boolean
        default: false
      align_openapi:
        description: "Enable OpenAPI Alignment?"
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Update openapi-connector
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BALLERINA_BOT_TOKEN }}

      - name: Get Ballerina Version
        run: |
          BAL_VERSION=$(grep -w 'ballerinaLangVersion' gradle.properties | cut -d= -f2 | rev | cut --complement -d- -f1 | rev)
          if [ -z "$BAL_VERSION" ]; then
              BAL_VERSION="latest"
          fi
          echo "BAL_VERSION=$BAL_VERSION" >> $GITHUB_ENV
          echo "Ballerina Version: $BAL_VERSION"

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.3
        with:
          version: ${{ env.BAL_VERSION }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21.0.3

      - name: Set ENV Variables
        run: |
          echo -e '${{ toJson(secrets) }}' | jq -r 'to_entries[] | .key + "=" + .value' >> $GITHUB_ENV

      - name: Remove Specific Files if They Exist
        working-directory: ballerina
        run: |
          rm -f client.bal utils.bal types.bal
          rm -f aligned_ballerina_openapi.json flattened_openapi.json openapi.json

      - name: Download or Copy openapi.json
        run: |
          if [ -n "${{ inputs.openapi_url }}" ]; then
            echo "Downloading openapi.json from provided URL..."
            wget -O ballerina/openapi.json "${{ inputs.openapi_url }}"
          else
            echo "Using existing openapi.json from docs/spec directory..."
            cp docs/spec/openapi.json ballerina/openapi.json
          fi

      - name: Flatten OpenAPI Specification
        working-directory: ballerina
        run: |
          if [ "${{ inputs.flatten_openapi }}" == 'true' ]; then
            echo "Flattening OpenAPI Specification..."
            bal openapi flatten -i openapi.json
          else
            echo "Skipping OpenAPI flattening."
            cp openapi.json flattened_openapi.json
          fi

      - name: Align OpenAPI Specification
        working-directory: ballerina
        run: |
          if [ "${{ inputs.align_openapi }}" == 'true' ]; then
            echo "Aligning OpenAPI Specification..."
            bal openapi align -i flattened_openapi.json
          else
            echo "Skipping OpenAPI alignment."
            cp flattened_openapi.json aligned_ballerina_openapi.json
          fi

      - name: Generate Ballerina Code
        working-directory: ballerina
        run: |
          echo "Generating Ballerina code from OpenAPI Specification..."
          bal openapi -i aligned_ballerina_openapi.json --mode client

      - name: Post cleanup
        working-directory: ballerina
        run: rm -f openapi.json flattened_openapi.json aligned_ballerina_openapi.json

      - name: Build the Package
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: |
          ./gradlew build -x test
          ./gradlew test

      - name: Configure Git Identity
        run: |
          git config user.name "chathushkaayash"
          git config user.email "chathushkaayash@gmail.com"

      - name: Commit and Push Changes
        run: |
          git add ballerina/
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "[Automated] Update Ballerina OpenAPI Connector"
            gh pr create --title "Update OpenAPI Connector" --body "Automated update of the OpenAPI-based Ballerina connector." --base main --head update-openapi-connector || gh pr merge update-openapi-connector --auto --merge
          fi
