name: Update openapi-connector

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      openapi_url:
        description: "URL of the OpenAPI JSON (Optional)"
        required: false
        type: string

jobs:
  build:
    name: Update openapi-connector
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Ballerina Version
        run: |
          BAL_VERSION=$(grep -w 'ballerinaLangVersion' gradle.properties | cut -d= -f2 | rev | cut --complement -d- -f1 | rev)
          if [ -z "$BAL_VERSION" ]; then
              BAL_VERSION="latest"
          fi
          echo "BAL_VERSION=$BAL_VERSION" >> $GITHUB_ENV
          echo "Ballerina Version: $BAL_VERSION"

      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.3
        with:
          version: ${{ env.BAL_VERSION }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21.0.3

      - name: Set ENV Variables
        run: |
          echo -e '${{ toJson(secrets) }}' | jq -r 'to_entries[] | .key + "=" + .value' >> $GITHUB_ENV

      - name: Remove Specific Files if They Exist
        working-directory: ballerina
        run: |
          rm -f client.bal utils.bal types.bal
          rm -f aligned_ballerina_openapi.json flattened_openapi.json openapi.json

      - name: Download or Copy openapi.json
        working-directory: ballerina
        run: |
          if [ -n "${{ inputs.openapi_url }}" ]; then
            echo "Downloading openapi.json from provided URL..."
            wget -O openapi.json "${{ inputs.openapi_url }}"
          else
            echo "Using existing openapi.json from docs/spec directory..."
            cp docs\spec\openapi.json openapi.json
          fi

      - name: Flatten OpenAPI Specification
        working-directory: ballerina
        run: bal openapi flatten -i openapi.json

      - name: Align OpenAPI Specification
        working-directory: ballerina
        run: bal openapi align -i flattened_openapi.json

      - name: Generate Ballerina Code
        working-directory: ballerina
        run: bal openapi -i aligned_ballerina_openapi.json --mode client

      - name: Post cleanup
        working-directory: ballerina
        run: rm -f openapi.json flattened_openapi.json aligned_ballerina_openapi.json

      - name: Build the Package
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: |
          ./gradlew build -x test
          ./gradlew test
